name: Vue2 CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 指定容器将工具缓存路径存放到 /toolcache ，该目录actRunner会默认持久化它
      RUNNER_TOOL_CACHE: /toolcache

    steps:
#      - name: Set timezone
#        uses: szenius/set-timezone@v2.0 # 设置执行环境的时区
#        with:
#          timezoneLinux: "Asia/Shanghai"
#          timezoneMacos: "Asia/Shanghai"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Docker
        uses: papodaca/install-docker-action@main

      - name: Log in to private Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ vars.DOCKER_REGISTRY }}/tudan/vue2-juel:$(date +%Y%m%d%H) .
          docker push ${{ vars.DOCKER_REGISTRY }}/tudan/vue2-juel:$(date +%Y%m%d%H)
